-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: shared/node_modules/.bin/prettier
        language: node
        files: shared/.*\.js$
        args: [
            '--single-quote',
            '--trailing-comma', 'es5',
            '--tab-width', '2',
            '--no-bracket-spacing',
            '--parser', 'flow',
            '--no-semi',
            '--print-width', '100',
            '--write']
    -   id: eslint
        name: eslint
        entry: shared/node_modules/.bin/eslint
        language: node
        files: \.js$
        args: [
            '--quiet'
        ]
    -   id: flow
        name: flow
        entry: sh
        language: system
        files: \.js$
        args: [-c, cd shared && node_modules/.bin/flow]
-   repo: https://github.com/keybase/pre-commit-golang.git
    sha: 06cb541d5ec2ec6adc218f7862098c55b5b24fc1
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
