repos:
-   repo: local
    hooks:
    -   id: rn-story-mode
        name: rn-story-mode
        entry: shared/ios/Keybase/git-hook
        language: script
        files: shared/ios/Keybase/Storybook.m
    -   id: eslint
        name: eslint
        entry: shared/node_modules/.bin/eslint
        language: node
        files: \.(js|ts|tsx)$
        args: [
            '--quiet',
            '--resolve-plugins-relative-to shared'
        ]
    -   id: tsc
        name: tsc
        entry: node
        args: ['--max-old-space-size=4096', 'shared/node_modules/.bin/tsc', '-p', 'shared/tsconfig.json']
        language: node
        files: \.(ts|tsx)$
        pass_filenames: false
    -   id: prettier
        name: prettier
        entry: shared/node_modules/.bin/prettier --write
        language: node
        files: \.(js|ts|tsx)$
-   repo: https://github.com/keybase/pre-commit-golang.git
    rev: 314766a2c26b7f32641addbdb0e7e451320ff1f0
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
