-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: sh
        language: system
        files: \.js$
        args: [-c, cd shared && yarn run lintone --]
    -   id: flow
        name: flow
        entry: sh
        language: system
        files: \.js$
        args:
        - -c
        - cd shared && yarn run flow
-   repo: https://github.com/keybase/pre-commit-golang.git
    sha: 06cb541d5ec2ec6adc218f7862098c55b5b24fc1
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
