install:

environment:
  global:
    GOPATH: c:\work\
    KEYBASE_SERVER_URI: https://ci1.keybase.io
    CGO_ENABLED: 1
    GOARCH: 386
    GO15VENDOREXPERIMENT: 1
    CC: c:\MinGW\bin\gcc
    CPATH: C:\MinGW\include;C:\MinGW\include\ddk

# clone directory
clone_folder: c:\work\src\github.com\keybase\kbfs

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x86

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - SET PATH=%PATH%;c:\MinGW\bin
  - git clone git@github.com:keybase/kbfs-binary-windows.git c:\work\src\github.com\keybase\kbfs-binary-windows
  - cd c:\work\src\github.com\keybase\kbfs-binary-windows
# throwaway branch to check out locally at a specific tag  
  - git checkout -b dokan-v1.0.0-RC2 dokan-v1.0.0-RC2
  - copy dokan\dokan1.lib ..\kbfs\dokan
  - cd ..\kbfs\dokan
  - go test -i
  - go test -c
  - cd ..\libdokan
  - go test -i
  - go test -c
  - cd ..\kbfsdokan
  - go build
  - cd ..\test
  - go test -i
  - cd ..
# Eventually there will be more tests, but let's just start with these for now
#  - go list ./... | find /V "vendor" > testlist.txt
  - echo github.com/keybase/kbfs/libkbfs > testlist.txt
  - echo github.com/keybase/kbfs/test >> testlist.txt
  - for /f %%i in (testlist.txt) do (appveyor AddTest %%i -Outcome Running -Framework gotest -Filename %%i & go test -timeout 5m %%i && appveyor UpdateTest %%i -Outcome Passed -Framework gotest -Filename %%i -Duration 0) || (appveyor UpdateTest %%i -Outcome Failed -Framework gotest -Filename %%i -Duration 0 & exit /b 1) 

# to disable automatic builds
#build: off

# to run your custom scripts instead of automatic tests
test_script:
