# -----------------------------------------------------------------------------
#
#   REMINDER: If you edit this file, you'll most likely also want to edit
#   .circleci/config.yml in the kbfs repository!
#
# -----------------------------------------------------------------------------
version: 2
jobs:
  build:
    working_directory: ~/go-path/src/github.com/keybase/client
    parallelism: 1

    docker:
    - image: keybaseprivate/circleci-client@sha256:70d727f7de73d35a172d7dbd81628b3db62fbe252e91327f15d9adfabb58b4d5
      command: /sbin/init

    steps:
    ##
    ## Build.
    ##

    - checkout

    # Install JS dependencies.
    - run:
        working_directory: shared
        command: yarn install --pure-lockfile --ignore-engines --network-concurrency 1
    - run:
        working_directory: shared
        command: yarn global add react-native-cli
    - run:
        working_directory: shared
        command: yarn run rn-gobuild-android

    - run: ls -la $GOPATH/src/github.com/keybase/client/shared/android/keybaselib/keybaselib.aar

    # Build a debug version of the app
    # Bundle JS separately because doing it in the gradle build is buggy
    - run: mkdir -p shared/android/app/build/intermediates/{assets,res/merged}/releaseUnsigned
    - run:
        working_directory: shared
        environment:
          REACT_NATIVE_MAX_WORKERS: 1
        command: yarn run react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/build/intermediates/assets/releaseUnsigned/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/releaseUnsigned

    # Build app.
    #
    # If the below fails with e.g. 'License for package Android SDK
    # Build-Tools 27.0.3 not accepted.', that probably means that the
    # CircleCI docker needs to be rebuilt. As a short term hack, we could
    # do also append to the license file here.
    - run:
        working_directory: shared/android
        environment:
          TERM: dumb
          # Limit memory usage of gradle
          _JAVA_OPTIONS: -Xms512m -Xmx2048m
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
        command: ./gradlew --no-daemon --stacktrace assembleReleaseUnsigned -x bundleReleaseUnsignedJsAndAssets

    # TODO: Run device tests (see old versions of this file).
