version: 2
jobs:
  build:
    working_directory: ~/client
    parallelism: 1

    docker:
    - image: marceloneil/circleci-client@sha256:8d39a394d45a5e65832e9644423e725d5b2f6013b7c6b4df0813578b40365a39

    steps:
    ##
    ## Build.
    ##

    - checkout

    # Install JS dependencies.
    - run:
        working_directory: shared
        command: yarn install --pure-lockfile --ignore-engines --network-concurrency 1
    - run:
        working_directory: shared
        command: yarn global add react-native-cli npm
    - run:
        working_directory: shared
        command: yarn run rn-gobuild-android
    - run:
        working_directory: shared
        command: yarn jetify

    - run: ls -la shared/android/keybaselib/keybaselib.aar

    # Build a debug version of the app
    # Bundle JS separately because doing it in the gradle build is buggy
    - run: mkdir -p shared/android/app/build/intermediates/{assets,res/merged}/releaseUnsigned
    - run:
        working_directory: shared
        environment:
          REACT_NATIVE_MAX_WORKERS: 1
        command: yarn run react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/build/intermediates/assets/releaseUnsigned/index.android.bundle --assets-dest android/app/build/intermediates/res/merged/releaseUnsigned

    # Build app.
    #
    # If the below fails with e.g. 'License for package Android SDK
    # Build-Tools 27.0.3 not accepted.', that probably means that the
    # CircleCI docker needs to be rebuilt. As a short term hack, we could
    # do also append to the license file here.
    - run:
        working_directory: shared/android
        environment:
          TERM: dumb
          # Limit memory usage of gradle
          _JAVA_OPTIONS: -Xms512m -Xmx2048m
          GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
        command: ./gradlew --no-daemon --stacktrace assembleReleaseUnsigned -x bundleReleaseUnsignedJsAndAssets

    # TODO: Run device tests (see old versions of this file).
