name: Close Issues
on:
  issues:
    types: [opened]

jobs:
  close_issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check issue body for regex
      id: check_regex
      run: |
        if [[ ! "${{ github.event.issue.body }}" =~ 345567 ]]; then
          echo "::set-output name=should_close::true"
        else
          echo "::set-output name=should_close::false"
        fi

    - name: Close issue
      if: steps.check_regex.outputs.should_close == 'true'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            state: 'closed'
          })
